version: '3.9'

services:
  db:
    image: postgres:latest
    container_name: rinha_backend_db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - ./resources/seed.sql:/docker-entrypoint-initdb.d/init.sql

  app1: &app
    hostname: app1
    build:
      context: .
      dockerfile: Dockerfile
    container_name: rinha_backend_go_app1
    environment:
      - POSTGRES_HOST=db
    depends_on:
      - db

  app2:
    <<: *app
    hostname: app2
    container_name: rinha_backend_go_app2

  nginx: # Load Balancer
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - app1
      - app2
    ports:
      - "${APP_PORT}:8080"
